web:
  password: ""
  port: 8080
  tls: false
  cert_path: ""
  key_path: ""
  public_url: ""
task:
  sync_interval: 60
  player_logging: false
  player_login_message: "Player {username} has joined the server! Current online player count: {online_num}."
  player_logout_message: "Player {username} has left the server! Current online player count: {online_num}."
rcon:
  address: "127.0.0.1:25575"
  password: ""
  use_base64: false
  timeout: 5
rest:
  address: "http://127.0.0.1:8212"
  username: "admin"
  password: ""
  timeout: 5
save:
  path: "/path/to/your/Pal/Saved"
  decode_path: ""
  sync_interval: 120
  backup_interval: 14400
manage:
  kick_non_whitelist: false
