name: PST Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"
env:
  IMAGE_NAME: palworld-server-tool
  DOCKER_REGISTRY: jokerwho
jobs:
  build-image:
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.output-id.outputs.v }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - id: output-id
        run: |
          VERSION=prod
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "v=${VERSION}" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: version=v${{ steps.output-id.outputs.v }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-id.outputs.v }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
